### ISSUE TITLE
DBCC loginfo and showfilestats needs validation before attempting to execute in db loop

### ISSUE THREAD

**Issue by LetsGoRafting** [SQLAdrian/Lazydba#30]
https://github.com/SQLAdrian/Lazydba/blob/695540db421376271c1ad288b97875f34ea6eeeb/SQLSteward.sql#L1542

errors when:
DBCC showfilestats WITH NO_INFOMSGS;
DBCC loginfo WITH NO_INFOMSGS;'

When its in an AG (and not readable secondary I think) then this error

The target database, 'DBNameHere', is participating in an availability group and is currently not accessible for queries. Either data movement is suspended or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

The fix is joining the db name like this:

SELECT d.name, d.database_id, CASE WHEN d.replica_id IS NULL THEN 0 ELSE 1 END AS is_replica,         ar.secondary_role_allow_connections  
FROM sys.databases d  JOIN sys.availability_replicas ar on d.replica_id = ar.replica_id  JOIN sys.servers s ON s.name = ar.replica_server_name AND s.server_id = 0 /*local server*/ 
WHERE d.database_id = x  --current db id in sys.databases loop

Snippet taken from this article referencing the error and if it allows connections ms article:
https://social.technet.microsoft.com/Forums/ie/en-US/939c3cbe-193c-4f95-97f1-ac8690c0321a/sql-always-on-not-accessible-for-queries?forum=operationsmanagermgmtpacks

**Comment by SQLAdrian** [comment]
There is a check on line 1009
+ CASE WHEN CONVERT(INT,LEFT(CONVERT(NVARCHAR(2),SERVERPROPERTY ('productversion')),2)) >= **12** THEN ' AND replica_id IS NULL' ELSE '' END;
Only problem is it doesn't assume anyone is brave enough to run AGs on SQL 2012. I'll change server version to 11 or greater
