### ISSUE TITLE
Caching plans dm_exec_cached_plans.usecount needs cast as bigint

### ISSUE THREAD

**Issue by LetsGoRafting** [SQLAdrian/Lazydba#31]
AMsg 8115, Level 16, State 2, Procedure sqlsteward, Line 1613 [Batch Start Line 0]
Arithmetic overflow error converting expression to data type int.
On 22V2..

	, SUM(cast(usecounts as bigint)) [Total Use]
	, AVG(cast(usecounts as bigint)) [Avg Use]

cast as bigint be thine fix

**Comment by SQLAdrian** [comment]
Thanks for fixing this one
